services:
  - type: web
    name: hybrid-trading-bot
    runtime: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: starter
    
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: PORT
        value: "8080"
